export const UPDATE_REC_LIST = 'UPDATE_REC_LIST';
export const UPDATE_VISIBLE_REC_LIST = 'UPDATE_VISIBLE_REC_LIST';
export const UPDATE_CURRENT_REC = 'UPDATE_CURRENT_REC';
export const SET_LOADED = 'SET_LOADED';
