export const SET_AUTH_DATA = 'SET_AUTH_DATA';


// Data Actions
export const FIREBASE_CREATE_REC = 'FIREBASE_CREATE_REC';

export const UPDATE_RECS_LIST = 'UPDATE_RECS_LIST';
export const UPDATE_DISPLAY_RECS_LIST = 'UPDATE_DISPLAY_RECS_LIST';
export const UPDATE_RECRS_LIST = 'UPDATE_RECRS_LIST';

export const UPDATE_DISPLAY_RECS_SORT = 'UPDATE_DISPLAY_RECS_SORT';
export const UPDATE_DISPLAY_RECS_FILTER = 'UPDATE_DISPLAY_RECS_FILTER';
