export const SHOW_ONBOARD_POPUP = 'SHOW_ONBOARD_POPUP';
export const INCREMENT_CURRENT_STEP = 'INCREMENT_CURRENT_STEP';

export const FOCUS = "REACT_NATIVE_ROUTER_FLUX_FOCUS";
export const BACK = "REACT_NATIVE_ROUTER_FLUX_BACK_ACTION";
