export const ADD_RECR = 'ADD_RECR';
export const LOAD_RECRS_FROM_FIREBASE = 'LOAD_RECRS_FROM_FIREBASE';
export const UPDATE_RECR_STATS = 'UPDATE_RECR_STATS';
export const UPDATE_RECR = 'UPDATE_RECR';
