# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Chaz' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Chaz

  pod 'Mixpanel'

end
