export const SET_TITLE = 'SET_TITLE';
export const SET_FRIEND = 'SET_FRIEND';
export const SAVE_RECOMMENDATION = 'SAVE_RECOMMENDATION';
export const SET_REMINDER = 'SET_REMINDER';
export const DELETE_RECOMMENDATION = 'DELETE_RECOMMENDATION';
export const SET_STATUS = 'SET_STATUS';
export const SET_FILTER = 'SET_FILTER';
